#!/bin/bash

export PYTHONPATH=/opt/graphite/webapp && exec /usr/local/bin/gunicorn wsgi --timeout=600 --workers=4 --bind=0.0.0.0:8080 --log-file=/var/log/gunicorn.log --preload --pythonpath=/opt/graphite/webapp/graphite
